export const SINGLE_WORD_TELLS = [
  "delves", "delve", "showcasing", "underscores", "intricate", "intricacies",
  "meticulously", "pivotal", "realm", "across", "additionally", "comprehensive",
  "crucial", "enhancing", "exhibited", "insights", "notably", "particularly",
  "within", "aligns", "boasts", "bolstered", "embark", "emphasizing", "enduring",
  "enhance", "excels", "fostering", "garnered", "highlighting", "interplay",
  "landscape", "moreover", "robust", "tapestry", "testament", "vibrant", "vital",
  "seamlessly", "harness",
];

export const AI_OUTPUT_PHRASES = [
  "delve into",
  "delving into the intricacies of",
  "navigate the landscape",
  "navigating the complexities of",
  "in today's fast-paced world",
  "ever-evolving landscape",
  "evolving landscape",
  "it's worth noting",
  "it is important to note",
  "it's important to remember",
  "in the realm of",
  "stands as a testament to",
  "a testament to",
  "plays a pivotal role",
  "plays a crucial role",
  "in the heart of",
  "rich tapestry of",
  "underscores the importance of",
  "highlighting the significance of",
  "marks a significant shift",
  "key turning point",
  "indelible mark",
  "deeply rooted in",
  "valuable insights",
  "diverse array of",
  "rich and diverse",
  "vital role in",
  "when it comes to",
];

export const SELF_IDENTIFIER_FATAL = [
  "as an ai language model",
  "as of my last knowledge update",
  "as of my last training",
  "i do not have access to",
  "i'm sorry, but as an ai",
  "regenerate response",
  "based on the information provided",
  "as a language model",
];

export const HEDGING_PHRASES = [
  "can be considered",
  "may potentially",
  "could potentially",
  "is often regarded as",
  "tends to be",
  "generally speaking",
  "arguably",
  "somewhat",
  "relatively",
  "in many cases",
  "it should be noted that",
  "it could be argued",
  "to some extent",
  "by and large",
  "for the most part",
  "in most cases",
];

export const MARKETING_FLUFF = [
  "game-changer",
  "game-changing",
  "revolutionize",
  "revolutionary",
  "best-in-class",
  "world-class",
  "cutting-edge",
  "state-of-the-art",
  "synergy",
  "synergize",
  "unlock the potential",
  "drive value",
  "deliver results",
  "transformative",
  "disruptive",
  "next-generation",
  "innovative solutions",
  "robust solutions",
  "scalable solutions",
  "end-to-end",
  "turnkey",
  "holistic approach",
  "thought leadership",
  "circle back",
  "deep dive",
  "move the needle",
  "low-hanging fruit",
  "paradigm shift",
  "mission-critical",
];

export const SEO_CLICHES = [
  "in conclusion",
  "in today's digital landscape",
  "in this comprehensive guide",
  "in this article, we will explore",
  "as we move forward",
  "looking ahead",
  "stay ahead of the curve",
  "in the digital age",
  "in this ever-changing world",
  "without further ado",
  "let's dive in",
  "let's get started",
  "the bottom line is",
  "at the end of the day",
];

export const ALL_PHRASES = [
  ...AI_OUTPUT_PHRASES,
  ...HEDGING_PHRASES,
  ...MARKETING_FLUFF,
  ...SEO_CLICHES,
];
